### ISSUE TITLE
Ark Analysis can't install through PYPI

### ISSUE THREAD

**Issue by srivarra** [angelolab/ark-analysis#739]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**

Currently Ark cannot be installed via PYPI. It is due to the `requirements.txt` file not being found. 

```sh
Collecting ark-analysis
  Using cached ark-analysis-0.4.1.tar.gz (296 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/Users/srivarra/.pyenv/versions/3.8.13/envs/ark-3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/srivarra/.pyenv/versions/3.8.13/envs/ark-3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/srivarra/.pyenv/versions/3.8.13/envs/ark-3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/fy/q2szypn9325d_0g0nq049k300000gq/T/pip-build-env-ro_zvi_n/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/fy/q2szypn9325d_0g0nq049k300000gq/T/pip-build-env-ro_zvi_n/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/fy/q2szypn9325d_0g0nq049k300000gq/T/pip-build-env-ro_zvi_n/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 482, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/fy/q2szypn9325d_0g0nq049k300000gq/T/pip-build-env-ro_zvi_n/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 21, in <module>
      FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/fy/q2szypn9325d_0g0nq049k300000gq/T/pip-install-__yl7pxm/ark-analysis_442d8caf3e654a1482fb20edd3df73f3/requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Expected behavior**

It should gather the requirements properly and install them, alongside `Ark` directly.

**To Reproduce**

Run `pip install ark-analysis` in a fresh python environment.

**Comment by alex-l-kong** [comment]
Ideally the same email address used to register the main PyPI account. I can set a dummy username and password for the computational team to use.

**Comment by ngreenwald** [comment]
We should switch them both to the angelolab gmail account so you guys have access
