### ISSUE TITLE
Error during installation of pyFlowSom

### ISSUE THREAD

**Issue by genomelab** [angelolab/ark-analysis#979]
Having trouble installing ark-analysis, particularly pyFlowSom on a python environment (3.11.3).  Mac environment (intel based)

This is the error:
Collecting pyFlowSOM==0.1.14 (from ark-analysis)
  Using cached pyFlowSOM-0.1.14.tar.gz (125 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "/Users/shahab/.local/share/virtualenvs/ark-sUNPyUwW-python/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/shahab/.local/share/virtualenvs/ark-sUNPyUwW-python/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/shahab/.local/share/virtualenvs/ark-sUNPyUwW-python/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/t0/892s95fn4cn9f26yrr2m0k_80000gq/T/pip-build-env-9r300gtd/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/t0/892s95fn4cn9f26yrr2m0k_80000gq/T/pip-build-env-9r300gtd/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/t0/892s95fn4cn9f26yrr2m0k_80000gq/T/pip-build-env-9r300gtd/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 17, in <module>
        File "/private/var/folders/t0/892s95fn4cn9f26yrr2m0k_80000gq/T/pip-build-env-9r300gtd/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 973, in cythonize
          module_list, module_metadata = create_extension_list(
                                         ^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/t0/892s95fn4cn9f26yrr2m0k_80000gq/T/pip-build-env-9r300gtd/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 816, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/private/var/folders/t0/892s95fn4cn9f26yrr2m0k_80000gq/T/pip-build-env-9r300gtd/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
          raise ValueError(error_msg)
      ValueError: 'src/pyFlowSOM/cyFlowSOM.pyx' doesn't match any files
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

Any ideas what may be causing the issue?  

Thanks

**Comment by genomelab** [comment]
The issue was fixed with using python 3.8.16. (had tried 3.9.12 but that had failed as well).
